-- Velvel, flott å se dere er kommet så langt
-- 
-- Her er en nøtt å bryne seg på, man kan bare ønske lykke til!
-- 
-- Neste stopp er så enkelt som
-- 59.969125, 10.abcdef 
--
--
-- a) Ulykke bringer tallet
-- b) Alle gode ting er...
-- c) Hvor mange ganger har Philip Ingebrigtsen vunnet 1500m i norgesmesterskap?
-- d) what b said
-- e) what d said
-- f) Yatzy!
